### ISSUE TITLE
 "'auto' return without trailing return type; deduced return types are a C++14 extension"

### ISSUE THREAD

**Issue by bemoregt** [BlueCocoa/mashiro#3]
Hi, @BlueCocoa 

I met this error when run your code.

"'auto' return without trailing return type; deduced return types are a C++14 extension"

How can I run your code my c++14 ?

Thanks in advance ~
Best,
@bemoregt.

**Comment by BlueCocoa** [comment]
Make sure you have a c++14 compatible compiler, e.g, gcc > 4.8. And then add compile option "-std=c++14". 
But next time, you should google it yourself.
